
public class HelloWorld {
	/**(이스케이프를 두번 사용해서 해결)
	 * Generated by the IBM IDL-toJava compiler, version 1.0
	 * from F:\TestRoot\apps\a1\units\include\PolicyHome.idl
	 * Wednesday, Jun 17, 1998 6:44:40 o' clock AM GMT+00:00
	 * */
	
	public static void main(String[] args) {
		System.out.print("Hell");
		System.out.print("o world");
	}
}
